apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
 namespace: cloudethix-rahuls
 labels:
   app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: rahuls086/cloudethix-nginix-rahuls:letest
        ports:
        - containerPort: 80
